### ISSUE TITLE
Navigate without mouse

### ISSUE THREAD

**Issue by iman99** [ervandew/screen#35]
How can I navigate without using mouse on screen?

**Comment by ervandew** [comment]
What are you looking to do?

You can check out the gnu screen man page and read the 'DEFAULT KEY BINDINGS' section:

    $ man screen

or online: https://www.gnu.org/software/screen/manual/screen.html#Commands

**Comment by iman99** [comment]
![screenshot_20180729_100005](https://user-images.githubusercontent.com/4252896/43362174-c27cfbac-92d2-11e8-82b9-abb4281d977e.jpeg)
Here's my screen shots. I want to move to bottom(on terminal) I have read the keybindings, nothing works

**Comment by ervandew** [comment]
If you are using gnu screen then the prefix key is `<ctrl-a>` so every command starts with that.
In gnu screen the splits are referred to as 'regions' and the simplest way to navigate them is using:

`<ctrl-a><tab>`

to cycle to the next region.

If you are using tmux then the prefix key is `<ctrl-b>` so every command starts with that.
In tmux the splits are referred to as 'panes' and the simplest way to navigate them is using:

`<ctrl-b>o`

to cycle to the next pane.
