### ISSUE TITLE
Open two terminal

### ISSUE THREAD

**Issue by iman99** [ervandew/screen#36]
Is it possible to open two terminal on screen? How to do it? And how can I navigate through it?

**Comment by ervandew** [comment]
If you are using gnu screen you can split horizontally using:

`<ctrl-a>S`

or vertically using:

`<ctrl-a>|`

If you are using tmux you can split horizontally using:

`<ctrl-b>%`

or vertically using:

`<ctrl-b>"`


> And how can I navigate through it?

See my response to your other issue.
